config/routes.rb
FireflyApp::Application.routes.draw do
  resources :providers

  get "healthcare/index"
  get "user/index"
  get "user/edit"
  get "user/results"
  get "user/success"
  devise_for :users
  get "site/index"
  get "site/kevin"
  get "site/allen"

  get "site/NeedsModal"

  get "site/PrioritiesModal"

  get "site/ProviderModal"

  get "site/RecommendationModal"

  root 'site#index'

  

end

app/models/provider.rb
class Provider < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def stored_location_for(resource)
    nil
  end
  def after_sign_in_path_for(resource_or_scope)
    user_index_path
  end

end

app/controllers/healthcare_controller.rb
class HealthcareController < ApplicationController
  require 'faraday'
  require 'logger'
  def index
    #api = HealthCare::Client.new
    # Find restaurants
    resp_text="%&<?xml version='1.0' encoding='UTF-8'?>
<PrivateOptionsAPIRequest>
	<ProductDetailsForSmallGroupRequest>
		<ProductIDs>
			<ProductID>38927UT015</ProductID>
		</ProductIDs>
	</ProductDetailsForSmallGroupRequest>
</PrivateOptionsAPIRequest>&"
    #resp = api.publicOptions(resp_text)
    #@data=JSON.parse(resp)
    #@count=@data['total_entries']
    #@page=@data['current_page']
    #@restaurants=@data['restaurants']
    myUrl="http://api.finder.healthcare.gov/v2.0"
    conn = Faraday.new(:url=> myUrl) do |builder|
      conn.post '/PrivateOption',resp_text
      builder.response :logger #logging stuff
      builder.use Faraday::Adapter::NetHttp #default adapter for Net::HTTP
    end

    res = conn.post do |request|
      request.url myUrl
      request.body = resp_text
    end

    puts res.body
  end

  module HealthCare
    class Error < StandardError ; end

    module Request
      API_BASE = "http://api.finder.healthcare.gov/v2.0/"

      def connection
        connection = Faraday.new(API_BASE) do |c|
          c.use (Faraday::Request::UrlEncoded)
          c.use (Faraday::Response::Logger)     # log request & response to STDOUT
          c.use (Faraday::Adapter::NetHttp)
          c.response :xml,  :content_type => /\bxml$/
        end
      end

      def request(method, path, params={}, raw=false)
        headers = {'Accept' => 'application/xml'}
        path = "#{path}"

        response = connection.send(method, path, params) do |request|
          request.url(path, params)
        end

        if [404, 403, 400].include?(response.status)
          raise HealthCare::Error, response.body["error"]
        end

        raw ? response : response.body
      end

      def get(path, params={})
        request(:get, path, params)
      end
    end

    class Client
      include Request

      def publicOptions(options={})
        post("/publicoptions",options)
      end

      def countries
        get("/countries")
      end

      def cities(country=nil)
        get("/cities")
      end

      def restaurants(options={})
        get("/restaurants", options)
      end

      def restaurant(id)
        get("/restaurants/#{id}")
      end
    end

  end
end

app/controllers/providers_controller.rb
class ProvidersController < ApplicationController
  before_action :set_provider, only: [:show, :edit, :update, :destroy]

  # GET /providers
  # GET /providers.json
  def index
    @providers = Provider.all
  end

  # GET /providers/1
  # GET /providers/1.json
  def show
  end

  # GET /providers/new
  def new
    @provider = Provider.new
  end

  # GET /providers/1/edit
  def edit
  end

  # POST /providers
  # POST /providers.json
  def create
    @provider = Provider.new(provider_params)

    respond_to do |format|
      if @provider.save
        format.html { redirect_to @provider, notice: 'Provider was successfully created.' }
        format.json { render action: 'show', status: :created, location: @provider }
      else
        format.html { render action: 'new' }
        format.json { render json: @provider.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /providers/1
  # PATCH/PUT /providers/1.json
  def update
    respond_to do |format|
      if @provider.update(provider_params)
        format.html { redirect_to @provider, notice: 'Provider was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @provider.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /providers/1
  # DELETE /providers/1.json
  def destroy
    @provider.destroy
    respond_to do |format|
      format.html { redirect_to providers_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_provider
      @provider = Provider.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def provider_params
      params.require(:provider).permit(:pname, :location, :price, :copay)
    end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  before_filter :authenticate_user!, :except => [:index,:kevin]

  def index
  end

  def kevin

  end

  def allen

  end

  def addUserInfo

  end

  def save_adduserinfo

  end

  def NeedsModal

  end

  def PrioritiesModal

  end

  def ProviderModal

  end

  def RecommendationModal

  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def index
    @user=User.find(:all)
  end

  def edit
    index
  end

  def info

  end

  def medical

  end

  def results

  end

  def success

  end


  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(provider_params)
        format.html { redirect_to root_path, notice: 'Provider was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @provider.errors, status: :unprocessable_entity }
      end
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/healthcare_helper.rb
module HealthcareHelper
end

app/helpers/providers_helper.rb
module ProvidersHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/healthcare/index.html.erb
<h1>Healthcare#index</h1>
<p>Find me in app/views/healthcare/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FireflyApp</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container-fluid">
  <nav class="navbar navbar-default" role="navigation">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1"> <span class="sr-only">Toggle navigation</span><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span></button><%= link_to "Firefly", root_path, class:'navbar-brand'%>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">


      </ul>

      <ul class="nav navbar-nav navbar-right" id="login-area">
        <p class="navbar-text pull-right">
          <% if user_signed_in? %>
              Logged in as <strong><%= current_user.email %></strong>.
              <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
              <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
          <% else %>
              <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
              <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
          <% end %>
          </ul>
    </div>

  </nav>
  <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
  <% end %>
  <% if alert %>
      <p class="alert alert-error"><%= alert %></p>
  <% end %>
  <%= yield %>
</div>
</body>
</html>

app/views/providers/_form.html.erb
<%= form_for(@provider) do |f| %>
  <% if @provider.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@provider.errors.count, "error") %> prohibited this provider from being saved:</h2>

      <ul>
      <% @provider.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :pname %><br>
    <%= f.text_field :pname %>
  </div>
  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :copay %><br>
    <%= f.text_field :copay %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/providers/edit.html.erb
<h1>Editing provider</h1>

<%= render 'form' %>

<%= link_to 'Show', @provider %> |
<%= link_to 'Back', providers_path %>

app/views/providers/index.html.erb
<h1>Listing providers</h1>

<table>
  <thead>
    <tr>
      <th>Pname</th>
      <th>Location</th>
      <th>Price</th>
      <th>Copay</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @providers.each do |provider| %>
      <tr>
        <td><%= provider.pname %></td>
        <td><%= provider.location %></td>
        <td><%= provider.price %></td>
        <td><%= provider.copay %></td>
        <td><%= link_to 'Show', provider %></td>
        <td><%= link_to 'Edit', edit_provider_path(provider) %></td>
        <td><%= link_to 'Destroy', provider, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Provider', new_provider_path %>

app/views/providers/new.html.erb
<h1>New provider</h1>

<%= render 'form' %>

<%= link_to 'Back', providers_path %>

app/views/providers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Pname:</strong>
  <%= @provider.pname %>
</p>

<p>
  <strong>Location:</strong>
  <%= @provider.location %>
</p>

<p>
  <strong>Price:</strong>
  <%= @provider.price %>
</p>

<p>
  <strong>Copay:</strong>
  <%= @provider.copay %>
</p>

<%= link_to 'Edit', edit_provider_path(@provider) %> |
<%= link_to 'Back', providers_path %>

app/views/site/DoctorsModal.html.erb
<div class="container">
			<p>
				Who is your primary care doctor?
			</p>
			<div class="row">
		  		<div class="col-lg-6">
		    		<div class="input-group">
		      			<span class="input-group-btn">
		       		  		<button class="btn btn-default" type="button">Search</button>
		      			</span>
		      			<input type="text" class="form-control">
		   			 </div><!-- /input-group -->
		  		</div><!-- /.col-lg-6 -->
		  	</div>
		</div>
		<div class="modal fade">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title">Primary Doctor Selection</h4>
      </div>
      <div class="modal-body">
      	<div class="container">
			<p>
				Who is your primary care doctor?
			</p>
			<div class="row">
		  		<div class="col-lg-6">
		    		<div class="input-group">
		      			<span class="input-group-btn">
		       		  		<button class="btn btn-default" type="button">Search</button>
		      			</span>
		      			<input type="text" class="form-control">
		   			 </div><!-- /input-group -->
		  		</div><!-- /.col-lg-6 -->
		  	</div>
		</div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

app/views/site/Landing.html.erb
<div class="border-form-div">

	<h2>Firefly Illuminating Health and Wellness</h2>

	<p>
		Welcome to Firefly, the portal that  lets you access information so you can choose insurance, doctors and filling prescriptions that are
		tailored to your healthcare needs and goals. We aim to provide you the best options, all in one place.
	</p>

	<p>
		Find a way to better living and a healthier life with Firefly!
	</p>
	<p>
		<button class="btn btn-lg btn-success">
			Start
		</button>
	</p>

</div>

app/views/site/NeedsModal.html.erb
<div class="container">
<p>
<div class="modal fade">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title">Primary Doctor Selection</h4>
      </div>
      <div class="modal-body">
      	<div class="container">
			<p>
				Who is your primary care doctor?
			</p>
			<div class="row">
		  		<div class="col-lg-6">
		    		<div class="input-group">
		      			<span class="input-group-btn">
		       		  		<button class="btn btn-default" type="button">Search</button>
		      			</span>
		      			<input type="text" class="form-control">
		   			 </div><!-- /input-group -->
		  		</div><!-- /.col-lg-6 -->
		  	</div>
		</div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
</p>
</div>

app/views/site/PrioritiesModal.html.erb
<div class="modal fade">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title">Primary Doctor Selection</h4>
      </div>
      <div class="modal-body">
      	<div class="container">
			<p>
				Who is your primary care doctor?
			</p>
			<div class="row">
		  		<div class="col-lg-6">
		    		<div class="input-group">
		      			<span class="input-group-btn">
		       		  		<button class="btn btn-default" type="button">Search</button>
		      			</span>
		      			<input type="text" class="form-control">
		   			 </div><!-- /input-group -->
		  		</div><!-- /.col-lg-6 -->
		  	</div>
		</div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

app/views/site/ProviderModal.html.erb
<div class="modal fade">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title">Primary Doctor Selection</h4>
      </div>
      <div class="modal-body">
      	<div class="container">
			<p>
				Who is your primary care doctor?
			</p>
			<div class="row">
		  		<div class="col-lg-6">
		    		<div class="input-group">
		      			<span class="input-group-btn">
		       		  		<button class="btn btn-default" type="button">Search</button>
		      			</span>
		      			<input type="text" class="form-control">
		   			 </div><!-- /input-group -->
		  		</div><!-- /.col-lg-6 -->
		  	</div>
		</div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

app/views/site/RecommendationModal.html.erb
<div class="modal fade">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title">Recommendations</h4>
      </div>
      <div class="modal-body">
      	<div class="container">
			<div class="btn-group" data-toggle="buttons">
			  <label class="btn btn-primary">
			    <input type="radio" name="options" id="option1"> Option 1
			  </label>
			  <label class="btn btn-primary">
			    <input type="radio" name="options" id="option2"> Option 2
			  </label>
			  <label class="btn btn-primary">
			    <input type="radio" name="options" id="option3"> Option 3
			  </label>
			</div>
		</div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

app/views/site/allen.html.erb
<p>
	Site#index Find me in app/views/site/index.html.erb
</p>

<div class="form-signin" role="form" 
	<h2 class= "form-signin-heading"> Enrolee 2222 Information </h2>
	<input type="email" class="form-control" placeholder="Email address" required="" autofocus="">
	<input type="password" class="form-control" placeholder="Password" required="">
	<p>
		Please provide some details about the enrolee:
	</p>
	<p>
		Date of Birth
		<button class="btn btn-lg btn-info">
			__/__/____</button>
	</p>
	<p>
		Home address ZIP code
		<button class="btn btn-lg btn-info">
			_____</button>
	</p>
	<p>
		<button class="btn btn-lg btn-success">
			Next
		</button>
	</p>
</div>


<div class="container">
	<h2> Enrolee Information </h2>
	<p>
		Please provide some details about the enrolee:
	</p>
	<p>
		Date of Birth
		<button class="btn btn-lg btn-info">
			__/__/____</button>
	</p>
	<p>
		Home address ZIP code
		<button class="btn btn-lg btn-info">
			_____</button>
	</p>
	<p>
		<button class="btn btn-lg btn-success">
			Next
		</button>
	</p>
</div>

<div class="container">
	<h2> Pre-existing Conditions</h2>
	<p>
		Do you have a specific condition or conditions you need care for?  Select all that apply:
	</p>
	<p>
		<button class="btn btn-lg btn-default">
			Lung Cancer
		</button>
		<button class="btn btn-lg btn-default">
			Breast Cancer
		</button>
		<button class="btn btn-lg btn-default">
			Prostate Cancer
		</button>
	</p>
	<p>
		<button class="btn btn-lg btn-default">
			Other Cancer
		</button>
		<button class="btn btn-lg btn-default">
			Diabeter
		</button>
		<button class="btn btn-lg btn-default">
			HIV/AIDS
		</button>
	</p>
	<p>
		<button class="btn btn-lg btn-success">
			Next
		</button>
		<button class="btn btn-lg btn-warning">
			Skip
		</button>
	</p>
</div>

<div class="container">
	<h2> Current Insurance </h2>
	<p>
		Who is your current provider?
	</p>
	<p>
		<button class="btn btn-lg btn-default">
			Kaiser
		</button>
		<button class="btn btn-lg btn-default">
			Health Net
		</button>
		<button class="btn btn-lg btn-default">
			Blue Cross
		</button>
	</p>
	<p>
		<button class="btn btn-lg btn-success">
			Next
		</button>
		<button class="btn btn-lg btn-warning">
			Skip
		</button>
	</p>
</div>

<div class="container">
	<h2> Doctor - Primary Care Provider </h2>
	<p>
		Who is your primary care doctor?
	</p>
	<p>
		This should be a textfield:
		<button class="btn btn-lg btn-default">
			_______
		</button>
	</p>
	<p>
		optional yada yada yada - info aobut the doctor you just looked up.
	</p>
	<p>
		<button class="btn btn-lg btn-success">
			Next
		</button>
		<button class="btn btn-lg btn-warning">
			Skip
		</button>
	</p>
</div>

<div class="container">
	<h2> Priorities </h2>
	<p>
		Which are important to you?
	</p>
	<p>
		<button class="btn btn-lg btn-default">
			Save Money
		</button>
		<button class="btn btn-lg btn-default">
			Better Coverage
		</button>
		<button class="btn btn-lg btn-default">
			Specific Doctor
		</button>
	</p>
	<p>
		<button class="btn btn-lg btn-default">
			More Options
		</button>
		<button class="btn btn-lg btn-default">
			Browser
		</button>
	</p>
	<p>
		<button class="btn btn-lg btn-success">
			Next
		</button>
		<button class="btn btn-lg btn-warning">
			Skip
		</button>
	</p>
</div>

<div class="container">
	<h2> Search Results </h2>
	<p>
		Firefly recommends one of the following insurance plans.  Click on them to find out more.
	</p>
	<p>
		<button class="btn btn-lg btn-default">
			Kaiser
		</button>
		<button class="btn btn-lg btn-default">
			Health Net
		</button>
		<button class="btn btn-lg btn-default">
			Blue Cross
		</button>
	</p>
</div>

<div class="container">
	<h2> Kaiser Permanente </h2>
	<p>
		Plan Details:
	</p>
	<p>
		<table>
			<tr>
				<td>Individual Deductible</td<td>$5,000 deductible for medical & drugs</td>
			</tr>
			<tr>
				<td>Family Deductible</td><td>$10,000 deductible</td>
			</tr>
			<tr>
				<td>Preventative Care Copay</td><td>no cost (at least 1 yearly visit)</td>
			</tr>
			<tr>
				<td>Primary Care Visit Copay</td><td>$60*</td>
			</tr>
			<tr>
				<td>Specialty Care Visit Copay</td><td>$70</td>
			</tr>
			<tr>
				<td>Urgent Care Visit Copay</td><td>120**</td>
			</tr>
			<tr>
				<td>Generic Medication Copay</td><td>$19</td>
			</tr>
			<tr>
				<td>Lab Testing Copay</td><td>30%</td>
			</tr>
			<tr>
				<td>X-Ray Copay</td><td>30%</td>
			</tr>
			<tr>
				<td>Emergency Room Copay</td><td>$300</td>
			</tr>
			<tr>
				<td>High cost and infrequent services</td><td>30% of your plan's negotiated rate</td>
			</tr>
			<tr>
				<td>Preferred brand copay after Drug Deductible (if any)</td><td>$50</td>
			</tr>
			<tr>
				<td>Maximum Out-of-Pocket For One</td><td>$6350</td>
			</tr>
			<tr>
				<td>Maximum Out-of-Pocket For Family</td><td>$13,500</td>
			</tr>
		</table>
	</p>
	<p>
		<button class="btn btn-lg btn-success">
			Sign-Up
		</button>
		<button class="btn btn-lg btn-danger">
			Back
		</button>
	</p>
</div>

app/views/site/index.html.erb
<div class="jumbotron">
	<h2>Firefly Illuminating Health and Wellness</h2>

	<p>
		Welcome to Firefly, the portal that  lets you access information so you can choose insurance, doctors and filling prescriptions that are
		tailored to your healthcare needs and goals. We aim to provide you the best options, all in one place.
	</p>

	<p>
		Find a way to better living and a healthier life with Firefly! What are you waiting for?
	</p>
	<p>
      <%# link_to "Sign up today!", new_user_registration_path, :class => 'btn btn-lg btn-success'  %>
      <% if user_signed_in? %>

          <%= link_to 'Check our options!', user_index_path, :class => 'btn btn-lg btn-success' %>
          <%# link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
      <% else %>
          <%= link_to "Sign up now!", new_user_registration_path, :class => 'btn btn-lg btn-success'  %>
      <% end %>


	</p>
</div>

app/views/user/edit.html.erb
<h1>User#edit</h1>
<p>Find me in app/views/user/edit.html.erb</p>

app/views/user/success.html.erb
<div class="border-form-div" id="first_form">
  <h1 style="text-align: center;">Success you have selected a plan!</h1>
  <p>&nbsp;</p>
</div>